// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import {PRODUCTS} from './mock-products';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-stencil';
  products = PRODUCTS;
  events: string[] = [];

  onAddToCart(event): void {
    this.events.push(`Added product ${event.detail}`);
  }
}

<style>
  .content {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    text-align: center;
  }

  .product-list {
    display: flex;
    justify-content: space-evenly;
    align-items: center;
  }
  ul {
    list-style: none;
  }

</style>
<div class="content">
  <h1>Using &lt;acme-product-card&gt; web component in Angular (10.2)</h1>

  <div class="product-list">
    <acme-product-card *ngFor="let product of products" [attr.pid]="product.pid" [attr.badge]="product.badge" [attr.name]="product.name"
                       [attr.desc]="product.desc" [attr.image-src]="product.imageSrc" [attr.price]="product.price"
                       (addToCart)="onAddToCart($event)"></acme-product-card>
  </div>
  <ul id="events">Angular parent component events:
    <li *ngFor="let event of events">
      &#x2192; {{ event }}
    </li>
  </ul>

</div>

// react/src/App.js
import React, {useEffect, useRef, useState} from 'react';
import './App.css';
import {PRODUCTS} from "./mock-products";

const App = () => {

  const [events, setEvents] = useState([]);
  const productCardListRef = useRef(null);

  //Hook up event handling for the addToCart event dispatched by acme-product-card element
  useEffect(() => {
    const onAddToCard = event => setEvents(e => [...e, `Added product ${event.detail}`]);

    const targetRef = productCardListRef.current;
    targetRef.addEventListener('addToCart', onAddToCard);
    return () => targetRef.removeEventListener('addToCart', onAddToCard)
  }, []);

  return (
      <div className="App">
        <h1>Using &lt;acme-product-card&gt; web component in React (17).</h1>
        <div className="products" ref={productCardListRef}>
          {PRODUCTS.map(p => <acme-product-card key={p.pid}
                                      pid={p.pid}
                                      badge={p.badge}
                                      name={p.name}
                                      desc={p.desc}
                                      image-src={p.imageSrc}
                                      price={p.price}
                                      data-testid={`card-${p.pid}`}>
                          </acme-product-card>)}

        </div>
        <ul id="events">React parent component events:
          {events.map((eventMsg, index) => <li key={index}> &#x2192; {eventMsg} </li>)}
        </ul>
      </div>
  );
};

export default App;
